### ISSUE TITLE
First JavaScript Web App: Mark Todo as Done

### ISSUE THREAD

**Issue by codingbootcampseu** [timhe375/bootcamp-schedule#79]
- [ ] Add a checkbox to each todo in the todo list
- [ ] Mark the todo as done when the checkbox is checked
  - [ ] Use `text-decoration: line-through` for done todos
 
**Hints**

Use the `change` event to find out whether the status of a checkbox has changed.

**Example Solution and Comparison**

- [Example solution](https://codesandbox.io/s/github/coding-bootcamps-eu/lexample-todo-app/blob/mark-todo-as-done/) for this task
- [Comparison to previous task](https://github.com/coding-bootcamps-eu/lexample-todo-app/compare/logical-checks...mark-todo-as-done)
